### ISSUE TITLE
Docker image build fails due to cartography library dependencies

### ISSUE THREAD

**Issue by tonofll** [soundsensing/mlflow-easyauth#2]
When running docker image creation command
```

docker build -t my-mlflow-easyauth:latest .
```
It fails when building wheel for cartography

>       =============================DEBUG ASSISTANCE=============================
>       If you are seeing a compilation error please try the following steps to
>       successfully install cryptography:
>       1) Upgrade to the latest pip and try again. This will fix errors for most
>          users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
>       2) Read https://cryptography.io/en/latest/installation.html for specific
>          instructions for your platform.
>       3) Check our frequently asked questions for more information:
>          https://cryptography.io/en/latest/faq.html
>       4) Ensure you have a recent Rust toolchain installed:
>          https://cryptography.io/en/latest/installation.html#rust
>       5) If you are experiencing issues with Rust for *this release only* you may
>          set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
>       =============================DEBUG ASSISTANCE=============================
>   
>   error: Can not find Rust compiler
>   
>   ----------------------------------------
>   Failed building wheel for cryptography

This error is produced due to issue https://github.com/pyca/cryptography/issues/5771

It can be easily solved by upgrading pip in the Dockerfile

```
RUN set -x \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y \
    python3 python3-pip python3-setuptools python3-pandas supervisor gettext-ba$
    && python3 -m pip install -U pip \
    && pip3 install wheel \
    && pip3 install -r requirements.txt \
    && apt-get remove --purge --auto-remove -y ca-certificates && rm -rf /var/l$

```

**Comment by ajeyamk** [comment]
Hey @tonofll 

I was able to get past that by referring to [this section](https://cryptography.io/en/latest/installation/#debian-ubuntu) on Cryptography's documentation.

**Comment by tbrodbeck** [comment]
Thanks @tonofll

**Comment by jonnor** [comment]
Are there any changes needed in our Dockerfiles for this? The build seems to be fine here now.

**Comment by jonnor** [comment]
Closing as this should have been fixed now.
