### ISSUE TITLE
read-only mode

### ISSUE THREAD

**Issue by geobao** [soundsensing/mlflow-easyauth#5]
I am trying to figure out a way to start an mlflow server in read-only mode.
The use case is:
I log my metrics and stuff, then I want to share results. So I want to offer access to mlflow only for visual access and to prevent them to edit my results. Can this be done somehow?

**Comment by jonnor** [comment]
Hi @geobao. This requires more fine-grained access control, so it is not something we will do in this project.
Therefore I think this question is best asked to the mlflow maintainers. If you do, feel free to link the discussion here - that way it is easy for people to find it!
