### ISSUE TITLE
Error building the docker image

### ISSUE THREAD

**Issue by spicoflorin** [soundsensing/mlflow-easyauth#6]
Hello!

While building the docker image I got the following errors:

  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.7m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.7/c/_cffi_backend.o
      unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
      error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
      ----------------------------------------
  Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-cwf7m6js/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-8jfgnipl/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-vkjk842e --compile" failed with error code 1 in /tmp/pip-install-cwf7m6js/cffi/
  
  ----------------------------------------
Command "/usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-vkjk842e --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools>=40.6.0 wheel "cffi>=1.12; platform_python_implementation != 'PyPy'" setuptools-rust>=0.11.4" failed with error code 1 in None
The command '/bin/sh -c set -x     && apt-get update     && apt-get install --no-install-recommends --no-install-suggests -y     python3 python3-pip python3-setuptools python3-pandas supervisor gettext-base nginx apache2-utils python3-psycopg2     && pip3 install wheel     && pip3 install -r requirements.txt     && apt-get remove --purge --auto-remove -y ca-certificates && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1

**Comment by LucasKirsten** [comment]
To solve for my case, I switched the base image to be used on the Dockerfile, and added a installation of the git-all package. My final Dockerfile is like this:
```
FROM python:3.9

# pandas installed from Debian repos to avoid building C extensions
RUN set -x
RUN apt-get update
RUN apt-get install --no-install-recommends --no-install-suggests -y git-all
RUN pip3 install mlflow
RUN apt-get remove --purge --auto-remove -y ca-certificates && rm -rf /var/lib/apt/lists/*


# WWW (nginx)
RUN addgroup -gid 1000 www \
    && adduser -uid 1000 -H -D -s /bin/sh -G www www


COPY nginx.conf.template /app/nginx.conf.template

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./entry-point.sh /app/entry-point.sh

COPY ./webserver.sh /app/webserver.sh
COPY ./mlflow.sh /app/mlflow.sh

CMD ["/bin/bash", "/app/entry-point.sh"]
```

**Comment by mstefferson-cerebral** [comment]
I ran into the same issue. I was able to get it work by changing the Dockerfile code block to:

```
RUN set -x \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y \
    python3 python3-pip python3-setuptools python3-dev gcc libffi-dev python3-pandas supervisor gettext-base nginx apache2-utils python3-psycopg2 \
    && pip3 install --upgrade pip \
    && pip3 install wheel \
    && pip3 install -r requirements.txt \
    && apt-get remove --purge --auto-remove -y ca-certificates && rm -rf /var/lib/apt/lists/*
```

Changes:
* install `python3-dev gcc libffi-dev`
* upgrade pip

**Comment by mstefferson-cerebral** [comment]
Although, the docker run still fails for me, but at least it builds 🤷

**Comment by jonnor** [comment]
Fixed in master. Have also updated to latest mlflow, 2.1.x
